on: 
  workflow_dispatch:

name: 🚀 Deploy server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: as1.ultra-h.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
