name: Compile SAMP Gamemode

on:
  workflow_dispatch:
  push:
    branches: [cwj-v2]
  pull_request:
    branches: [cwj-v2]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile CWJ Filterscript
      run: |
        cd pawno
        scripts=$(find ../filterscripts -name "*.pwn")
        for script in $scripts; do (
          ./pawncc.exe "$script" --% -Dfilterscripts -;+ -(+ -d3
        ); done

    - name: Compile CWJ Gamemode
      run: |
        cd pawno
        ./pawncc.exe ../gamemodes/bb_freeroam.pwn --% -Dgamemodes -;+ -(+ -d3

    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Update compiled gamemode' && git push)
